package loc

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/alexei-led/archfit/v3/internal/model/fileclass"
	"github.com/alexei-led/archfit/v3/internal/syntax"
)

// TestClassifyFileAgreesWithTheWalk pins that one-file classification gives
// the walk's class to a file the walk visits, generated header included, and
// the path-only class to a file under a directory the walk skips.
func TestClassifyFileAgreesWithTheWalk(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	generated := "// Code generated by protoc. DO NOT EDIT.\n\npackage x\n"
	for _, rel := range []string{"internal/x/x.go", "target/x/x.go", ".hidden/x.go"} {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(generated), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	_, walked, _, err := RunWithConfig(root, syntax.FileClassConfig{})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct {
		rel  string
		want fileclass.FileClass
	}{
		{rel: "internal/x/x.go", want: walked["internal/x/x.go"]},
		{rel: "target/x/x.go", want: syntax.ClassifyFile("go", "target/x/x.go", nil, syntax.FileClassConfig{})},
		{rel: ".hidden/x.go", want: syntax.ClassifyFile("go", ".hidden/x.go", nil, syntax.FileClassConfig{})},
	} {
		if got := ClassifyFile(root, tc.rel, "go", syntax.FileClassConfig{}); got != tc.want {
			t.Errorf("%s: ClassifyFile = %v, want %v", tc.rel, got, tc.want)
		}
	}
	if walked["internal/x/x.go"] != fileclass.Generated {
		t.Fatalf("the walk did not sniff the generated header: %v", walked["internal/x/x.go"])
	}
	if _, ok := walked["target/x/x.go"]; ok {
		t.Fatal("the walk visited target/: the skipped-dir case is vacuous")
	}
}
