// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ports

import (
	"context"
	"sync"

	"github.com/alexei-led/archfit/internal/model/evidence"
	"github.com/alexei-led/archfit/internal/model/graph"
	"github.com/alexei-led/archfit/internal/scope"
)

// Ensure, that ExtractorMock does implement Extractor.
// If this is not the case, regenerate this file with moq.
var _ Extractor = &ExtractorMock{}

// ExtractorMock is a mock implementation of Extractor.
//
//	func TestSomethingThatUsesExtractor(t *testing.T) {
//
//		// make and configure a mocked Extractor
//		mockedExtractor := &ExtractorMock{
//			CoverageToolFunc: func() string {
//				panic("mock out the CoverageTool method")
//			},
//			ExtractFunc: func(ctx context.Context, s scope.Scope) (graph.Facts, evidence.Coverage, error) {
//				panic("mock out the Extract method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//		}
//
//		// use mockedExtractor in code that requires Extractor
//		// and then make assertions.
//
//	}
type ExtractorMock struct {
	// CoverageToolFunc mocks the CoverageTool method.
	CoverageToolFunc func() string

	// ExtractFunc mocks the Extract method.
	ExtractFunc func(ctx context.Context, s scope.Scope) (graph.Facts, evidence.Coverage, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// CoverageTool holds details about calls to the CoverageTool method.
		CoverageTool []struct {
		}
		// Extract holds details about calls to the Extract method.
		Extract []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S scope.Scope
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
	}
	lockCoverageTool sync.RWMutex
	lockExtract      sync.RWMutex
	lockName         sync.RWMutex
}

// CoverageTool calls CoverageToolFunc.
func (mock *ExtractorMock) CoverageTool() string {
	if mock.CoverageToolFunc == nil {
		panic("ExtractorMock.CoverageToolFunc: method is nil but Extractor.CoverageTool was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCoverageTool.Lock()
	mock.calls.CoverageTool = append(mock.calls.CoverageTool, callInfo)
	mock.lockCoverageTool.Unlock()
	return mock.CoverageToolFunc()
}

// CoverageToolCalls gets all the calls that were made to CoverageTool.
// Check the length with:
//
//	len(mockedExtractor.CoverageToolCalls())
func (mock *ExtractorMock) CoverageToolCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCoverageTool.RLock()
	calls = mock.calls.CoverageTool
	mock.lockCoverageTool.RUnlock()
	return calls
}

// Extract calls ExtractFunc.
func (mock *ExtractorMock) Extract(ctx context.Context, s scope.Scope) (graph.Facts, evidence.Coverage, error) {
	if mock.ExtractFunc == nil {
		panic("ExtractorMock.ExtractFunc: method is nil but Extractor.Extract was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   scope.Scope
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockExtract.Lock()
	mock.calls.Extract = append(mock.calls.Extract, callInfo)
	mock.lockExtract.Unlock()
	return mock.ExtractFunc(ctx, s)
}

// ExtractCalls gets all the calls that were made to Extract.
// Check the length with:
//
//	len(mockedExtractor.ExtractCalls())
func (mock *ExtractorMock) ExtractCalls() []struct {
	Ctx context.Context
	S   scope.Scope
} {
	var calls []struct {
		Ctx context.Context
		S   scope.Scope
	}
	mock.lockExtract.RLock()
	calls = mock.calls.Extract
	mock.lockExtract.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *ExtractorMock) Name() string {
	if mock.NameFunc == nil {
		panic("ExtractorMock.NameFunc: method is nil but Extractor.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedExtractor.NameCalls())
func (mock *ExtractorMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}
