// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package toolrun

import (
	"context"
	"sync"
)

// RunnerMock is a mock implementation of Runner for testing.
//
//	func TestSomething(t *testing.T) {
//	    runner := &toolrun.RunnerMock{
//	        DetectFunc: func(ctx context.Context, tool string) (ToolInfo, bool) { ... },
//	        RunFunc:    func(ctx context.Context, cmd ToolCmd) (Output, error) { ... },
//	    }
//	    ...
//	}
type RunnerMock struct {
	// DetectFunc mocks the Detect method.
	DetectFunc func(ctx context.Context, tool string) (ToolInfo, bool)

	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, cmd ToolCmd) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Detect holds details about calls to the Detect method.
		Detect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tool is the tool argument value.
			Tool string
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cmd is the cmd argument value.
			Cmd ToolCmd
		}
	}
	lockDetect sync.RWMutex
	lockRun    sync.RWMutex
}

// Detect calls DetectFunc.
func (m *RunnerMock) Detect(ctx context.Context, tool string) (ToolInfo, bool) {
	if m.DetectFunc == nil {
		panic("RunnerMock.DetectFunc is nil but Runner.Detect was called")
	}
	call := struct {
		Ctx  context.Context
		Tool string
	}{Ctx: ctx, Tool: tool}
	m.lockDetect.Lock()
	m.calls.Detect = append(m.calls.Detect, call)
	m.lockDetect.Unlock()
	return m.DetectFunc(ctx, tool)
}

// DetectCalls returns all calls that were made to Detect.
func (m *RunnerMock) DetectCalls() []struct {
	Ctx  context.Context
	Tool string
} {
	m.lockDetect.RLock()
	defer m.lockDetect.RUnlock()
	calls := make([]struct {
		Ctx  context.Context
		Tool string
	}, len(m.calls.Detect))
	copy(calls, m.calls.Detect)
	return calls
}

// Run calls RunFunc.
func (m *RunnerMock) Run(ctx context.Context, cmd ToolCmd) (Output, error) {
	if m.RunFunc == nil {
		panic("RunnerMock.RunFunc is nil but Runner.Run was called")
	}
	call := struct {
		Ctx context.Context
		Cmd ToolCmd
	}{Ctx: ctx, Cmd: cmd}
	m.lockRun.Lock()
	m.calls.Run = append(m.calls.Run, call)
	m.lockRun.Unlock()
	return m.RunFunc(ctx, cmd)
}

// RunCalls returns all calls that were made to Run.
func (m *RunnerMock) RunCalls() []struct {
	Ctx context.Context
	Cmd ToolCmd
} {
	m.lockRun.RLock()
	defer m.lockRun.RUnlock()
	calls := make([]struct {
		Ctx context.Context
		Cmd ToolCmd
	}, len(m.calls.Run))
	copy(calls, m.calls.Run)
	return calls
}
