// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package toolrun

import (
	"context"
	"io"
	"sync"
)

// Ensure, that RunnerMock does implement Runner.
// If this is not the case, regenerate this file with moq.
var _ Runner = &RunnerMock{}

// RunnerMock is a mock implementation of Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked Runner
//		mockedRunner := &RunnerMock{
//			DetectFunc: func(ctx context.Context, tool string) (ToolInfo, bool) {
//				panic("mock out the Detect method")
//			},
//			RunFunc: func(ctx context.Context, cmd ToolCmd) (Output, error) {
//				panic("mock out the Run method")
//			},
//			StreamFunc: func(ctx context.Context, cmd ToolCmd, consume func(io.Reader) error) (Output, error) {
//				panic("mock out the Stream method")
//			},
//		}
//
//		// use mockedRunner in code that requires Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// DetectFunc mocks the Detect method.
	DetectFunc func(ctx context.Context, tool string) (ToolInfo, bool)

	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, cmd ToolCmd) (Output, error)

	// StreamFunc mocks the Stream method.
	StreamFunc func(ctx context.Context, cmd ToolCmd, consume func(io.Reader) error) (Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Detect holds details about calls to the Detect method.
		Detect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tool is the tool argument value.
			Tool string
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cmd is the cmd argument value.
			Cmd ToolCmd
		}
		// Stream holds details about calls to the Stream method.
		Stream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cmd is the cmd argument value.
			Cmd ToolCmd
			// Consume is the consume argument value.
			Consume func(io.Reader) error
		}
	}
	lockDetect sync.RWMutex
	lockRun    sync.RWMutex
	lockStream sync.RWMutex
}

// Detect calls DetectFunc.
func (mock *RunnerMock) Detect(ctx context.Context, tool string) (ToolInfo, bool) {
	if mock.DetectFunc == nil {
		panic("RunnerMock.DetectFunc: method is nil but Runner.Detect was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Tool string
	}{
		Ctx:  ctx,
		Tool: tool,
	}
	mock.lockDetect.Lock()
	mock.calls.Detect = append(mock.calls.Detect, callInfo)
	mock.lockDetect.Unlock()
	return mock.DetectFunc(ctx, tool)
}

// DetectCalls gets all the calls that were made to Detect.
// Check the length with:
//
//	len(mockedRunner.DetectCalls())
func (mock *RunnerMock) DetectCalls() []struct {
	Ctx  context.Context
	Tool string
} {
	var calls []struct {
		Ctx  context.Context
		Tool string
	}
	mock.lockDetect.RLock()
	calls = mock.calls.Detect
	mock.lockDetect.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *RunnerMock) Run(ctx context.Context, cmd ToolCmd) (Output, error) {
	if mock.RunFunc == nil {
		panic("RunnerMock.RunFunc: method is nil but Runner.Run was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cmd ToolCmd
	}{
		Ctx: ctx,
		Cmd: cmd,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, cmd)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedRunner.RunCalls())
func (mock *RunnerMock) RunCalls() []struct {
	Ctx context.Context
	Cmd ToolCmd
} {
	var calls []struct {
		Ctx context.Context
		Cmd ToolCmd
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// Stream calls StreamFunc.
func (mock *RunnerMock) Stream(ctx context.Context, cmd ToolCmd, consume func(io.Reader) error) (Output, error) {
	if mock.StreamFunc == nil {
		panic("RunnerMock.StreamFunc: method is nil but Runner.Stream was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Cmd     ToolCmd
		Consume func(io.Reader) error
	}{
		Ctx:     ctx,
		Cmd:     cmd,
		Consume: consume,
	}
	mock.lockStream.Lock()
	mock.calls.Stream = append(mock.calls.Stream, callInfo)
	mock.lockStream.Unlock()
	return mock.StreamFunc(ctx, cmd, consume)
}

// StreamCalls gets all the calls that were made to Stream.
// Check the length with:
//
//	len(mockedRunner.StreamCalls())
func (mock *RunnerMock) StreamCalls() []struct {
	Ctx     context.Context
	Cmd     ToolCmd
	Consume func(io.Reader) error
} {
	var calls []struct {
		Ctx     context.Context
		Cmd     ToolCmd
		Consume func(io.Reader) error
	}
	mock.lockStream.RLock()
	calls = mock.calls.Stream
	mock.lockStream.RUnlock()
	return calls
}
