package initcfg_test

import (
	"strings"
	"testing"

	"github.com/alexei-led/archfit/internal/initcfg"
)

// commentedV1 is the shape that matters: a v1 config with authored comments,
// unrelated stanzas, and both retired coupling-gate knobs.
const commentedV1 = `# Generated by archfit config init — reviewed 2026-04-01
version: 1

# Analysis boundary. Do not narrow without asking platform.
exclude:
  - "vendor/**"

coupling:
  # Advisory floor, unrelated to the gate below.
  min_severity: medium
  gate:
    # MinBand is the band floor for the repository coupling score.
    min_band: serviceable
    # Tolerated drop against the stored baseline score.
    max_drop: 5

layers:
  - core
  - adapter

modules:
  billing:
    paths: ["internal/billing/**"]
    owner: team-money
`

func TestMigrateToV2_RewritesVersionAndRetiredGate(t *testing.T) {
	got := initcfg.MigrateToV2([]byte(commentedV1))

	if !got.Changed() {
		t.Fatalf("status = %q, want %q", got.Status, initcfg.MigrationRequired)
	}
	if got.FromVersion != 1 || got.ToVersion != initcfg.TargetSchemaVersion {
		t.Errorf("versions = %d → %d, want 1 → %d", got.FromVersion, got.ToVersion, initcfg.TargetSchemaVersion)
	}

	out := string(got.Output)
	if !strings.Contains(out, "version: 2\n") {
		t.Errorf("output did not bump the root version:\n%s", out)
	}
	for _, retired := range []string{"min_band", "max_drop"} {
		if strings.Contains(out, retired) {
			t.Errorf("output still carries the retired key %q:\n%s", retired, out)
		}
	}
	if !strings.Contains(out, "    distributed_monolith:\n") {
		t.Errorf("replacement stanza missing or misindented:\n%s", out)
	}
	if !strings.Contains(out, "      mode: warn") || !strings.Contains(out, "      max_new_seams: 0") {
		t.Errorf("replacement stanza is not warn/0:\n%s", out)
	}
	// Fail blocks a build. The migration must never infer it.
	if strings.Contains(out, "mode: fail") {
		t.Errorf("migration inferred fail mode:\n%s", out)
	}
}

// TestMigrateToV2_PreservesUnrelatedAuthoredYAML is the whole reason this is a
// line transform rather than a YAML round-trip: a marshaller would reflow the
// file and drop every comment the author wrote.
func TestMigrateToV2_PreservesUnrelatedAuthoredYAML(t *testing.T) {
	out := string(initcfg.MigrateToV2([]byte(commentedV1)).Output)

	for _, keep := range []string{
		"# Generated by archfit config init — reviewed 2026-04-01",
		"# Analysis boundary. Do not narrow without asking platform.",
		`  - "vendor/**"`,
		"  # Advisory floor, unrelated to the gate below.",
		"  min_severity: medium",
		"  billing:",
		"    owner: team-money",
	} {
		if !strings.Contains(out, keep) {
			t.Errorf("migration dropped authored content %q:\n%s", keep, out)
		}
	}
	// A comment directly above a removed key documents that key, so it goes
	// with it — leaving it behind would document a key that no longer exists.
	if strings.Contains(out, "MinBand is the band floor") {
		t.Errorf("migration kept a comment describing a removed key:\n%s", out)
	}
}

// TestMigrateToV2_IsByteIdempotent pins the contract that makes the migration
// safe to run in a sweep: a second pass changes nothing at all.
func TestMigrateToV2_IsByteIdempotent(t *testing.T) {
	first := initcfg.MigrateToV2([]byte(commentedV1))
	second := initcfg.MigrateToV2(first.Output)

	if second.Changed() {
		t.Errorf("second pass reports %q, want %q", second.Status, initcfg.MigrationAlreadyCurrent)
	}
	if string(second.Output) != string(first.Output) {
		t.Errorf("second pass changed bytes:\nfirst:\n%s\nsecond:\n%s", first.Output, second.Output)
	}
	if len(second.Changes) != 0 {
		t.Errorf("second pass reports edits %+v, want none", second.Changes)
	}
}

func TestMigrateToV2_ReportsTheSemanticChange(t *testing.T) {
	tests := []struct {
		name        string
		src         string
		wantChanged bool
		wantPolicy  bool
	}{
		{
			name:        "a version-only bump is mechanical",
			src:         "version: 1\nmodules:\n  a:\n    paths: [\"a/**\"]\n",
			wantChanged: true,
		},
		{
			name:        "retiring a gate changes what blocks a build",
			src:         "version: 1\ncoupling:\n  gate:\n    min_band: strong\n",
			wantChanged: true, wantPolicy: true,
		},
		{
			name: "a current config needs nothing",
			src:  "version: 2\ncoupling:\n  gate:\n    distributed_monolith:\n      mode: warn\n",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := initcfg.MigrateToV2([]byte(tc.src))
			if got.Changed() != tc.wantChanged {
				t.Errorf("changed = %v, want %v (status %q)", got.Changed(), tc.wantChanged, got.Status)
			}
			if hasPolicy := len(got.PolicyChanges) > 0; hasPolicy != tc.wantPolicy {
				t.Errorf("policy_changes = %v, want reported=%v", got.PolicyChanges, tc.wantPolicy)
			}
		})
	}
}

// TestMigrateToV2_OnlyTouchesTheRootVersion guards the one rewrite that could
// corrupt an unrelated stanza: a nested `version:` belongs to whatever declared
// it, not to the config schema.
func TestMigrateToV2_OnlyTouchesTheRootVersion(t *testing.T) {
	const src = "version: 1\nanalyzers:\n  scip:\n    version: 1\n"

	out := string(initcfg.MigrateToV2([]byte(src)).Output)
	if !strings.HasPrefix(out, "version: 2\n") {
		t.Errorf("root version not bumped:\n%s", out)
	}
	if !strings.Contains(out, "    version: 1\n") {
		t.Errorf("nested version was rewritten:\n%s", out)
	}
}

// TestMigrateToV2_PlacesTheStanzaInsideTheGateBlock guards against splicing the
// replacement next to a later stanza that happens to share the indentation.
func TestMigrateToV2_PlacesTheStanzaInsideTheGateBlock(t *testing.T) {
	const src = `version: 1
coupling:
  gate:
    min_band: strong
modules:
  billing:
    paths: ["internal/billing/**"]
`
	out := string(initcfg.MigrateToV2([]byte(src)).Output)
	gate := strings.Index(out, "    distributed_monolith:")
	modules := strings.Index(out, "modules:")
	if gate < 0 || modules < 0 {
		t.Fatalf("output missing gate stanza or modules block:\n%s", out)
	}
	if gate > modules {
		t.Errorf("replacement stanza landed after modules: — it must stay inside the gate block:\n%s", out)
	}
}
