package initcfg_test

import (
	"strings"
	"testing"

	"github.com/alexei-led/archfit/internal/initcfg"
)

// commentedV1 is the shape that matters: a v1 config with authored comments,
// unrelated stanzas, and both retired coupling-gate knobs.
const commentedV1 = `# Generated by archfit config init — reviewed 2026-04-01
version: 1

# Analysis boundary. Do not narrow without asking platform.
exclude:
  - "vendor/**"

coupling:
  # Advisory floor, unrelated to the gate below.
  min_severity: medium
  gate:
    # MinBand is the band floor for the repository coupling score.
    min_band: serviceable
    # Tolerated drop against the stored baseline score.
    max_drop: 5

layers:
  - core
  - adapter

modules:
  billing:
    paths: ["internal/billing/**"]
    owner: team-money
`

func TestMigrateToV2_RewritesVersionAndRetiredGate(t *testing.T) {
	got := initcfg.MigrateToV2([]byte(commentedV1))

	if !got.Changed() {
		t.Fatalf("status = %q, want %q", got.Status, initcfg.MigrationRequired)
	}
	if got.FromVersion != 1 || got.ToVersion != initcfg.TargetSchemaVersion {
		t.Errorf("versions = %d → %d, want 1 → %d", got.FromVersion, got.ToVersion, initcfg.TargetSchemaVersion)
	}

	out := string(got.Output)
	if !strings.Contains(out, "version: 2\n") {
		t.Errorf("output did not bump the root version:\n%s", out)
	}
	for _, retired := range []string{"min_band", "max_drop"} {
		if strings.Contains(out, retired) {
			t.Errorf("output still carries the retired key %q:\n%s", retired, out)
		}
	}
	if !strings.Contains(out, "    distributed_monolith:\n") {
		t.Errorf("replacement stanza missing or misindented:\n%s", out)
	}
	if !strings.Contains(out, "      mode: warn") || !strings.Contains(out, "      max_new_seams: 0") {
		t.Errorf("replacement stanza is not warn/0:\n%s", out)
	}
	// Fail blocks a build. The migration must never infer it.
	if strings.Contains(out, "mode: fail") {
		t.Errorf("migration inferred fail mode:\n%s", out)
	}
}

// TestMigrateToV2_PreservesUnrelatedAuthoredYAML is the whole reason this is a
// line transform rather than a YAML round-trip: a marshaller would reflow the
// file and drop every comment the author wrote.
func TestMigrateToV2_PreservesUnrelatedAuthoredYAML(t *testing.T) {
	out := string(initcfg.MigrateToV2([]byte(commentedV1)).Output)

	for _, keep := range []string{
		"# Generated by archfit config init — reviewed 2026-04-01",
		"# Analysis boundary. Do not narrow without asking platform.",
		`  - "vendor/**"`,
		"  # Advisory floor, unrelated to the gate below.",
		"  min_severity: medium",
		"  billing:",
		"    owner: team-money",
	} {
		if !strings.Contains(out, keep) {
			t.Errorf("migration dropped authored content %q:\n%s", keep, out)
		}
	}
	// A comment directly above a removed key documents that key, so it goes
	// with it — leaving it behind would document a key that no longer exists.
	if strings.Contains(out, "MinBand is the band floor") {
		t.Errorf("migration kept a comment describing a removed key:\n%s", out)
	}
}

// TestMigrateToV2_IsByteIdempotent pins the contract that makes the migration
// safe to run in a sweep: a second pass changes nothing at all.
func TestMigrateToV2_IsByteIdempotent(t *testing.T) {
	first := initcfg.MigrateToV2([]byte(commentedV1))
	second := initcfg.MigrateToV2(first.Output)

	if second.Changed() {
		t.Errorf("second pass reports %q, want %q", second.Status, initcfg.MigrationAlreadyCurrent)
	}
	if string(second.Output) != string(first.Output) {
		t.Errorf("second pass changed bytes:\nfirst:\n%s\nsecond:\n%s", first.Output, second.Output)
	}
	if len(second.Changes) != 0 {
		t.Errorf("second pass reports edits %+v, want none", second.Changes)
	}
}

func TestMigrateToV2_ReportsTheSemanticChange(t *testing.T) {
	tests := []struct {
		name        string
		src         string
		wantChanged bool
		wantPolicy  bool
	}{
		{
			name:        "a version-only bump is mechanical",
			src:         "version: 1\nmodules:\n  a:\n    paths: [\"a/**\"]\n",
			wantChanged: true,
		},
		{
			name:        "retiring a gate changes what blocks a build",
			src:         "version: 1\ncoupling:\n  gate:\n    min_band: strong\n",
			wantChanged: true, wantPolicy: true,
		},
		{
			name: "a current config needs nothing",
			src:  "version: 2\ncoupling:\n  gate:\n    distributed_monolith:\n      mode: warn\n",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := initcfg.MigrateToV2([]byte(tc.src))
			if got.Changed() != tc.wantChanged {
				t.Errorf("changed = %v, want %v (status %q)", got.Changed(), tc.wantChanged, got.Status)
			}
			if hasPolicy := len(got.PolicyChanges) > 0; hasPolicy != tc.wantPolicy {
				t.Errorf("policy_changes = %v, want reported=%v", got.PolicyChanges, tc.wantPolicy)
			}
		})
	}
}

// TestMigrateToV2_OnlyTouchesTheRootVersion guards the one rewrite that could
// corrupt an unrelated stanza: a nested `version:` belongs to whatever declared
// it, not to the config schema.
func TestMigrateToV2_OnlyTouchesTheRootVersion(t *testing.T) {
	const src = "version: 1\nanalyzers:\n  scip:\n    version: 1\n"

	out := string(initcfg.MigrateToV2([]byte(src)).Output)
	if !strings.HasPrefix(out, "version: 2\n") {
		t.Errorf("root version not bumped:\n%s", out)
	}
	if !strings.Contains(out, "    version: 1\n") {
		t.Errorf("nested version was rewritten:\n%s", out)
	}
}

// TestMigrateToV2_PlacesTheStanzaInsideTheGateBlock guards against splicing the
// replacement next to a later stanza that happens to share the indentation.
func TestMigrateToV2_PlacesTheStanzaInsideTheGateBlock(t *testing.T) {
	const src = `version: 1
coupling:
  gate:
    min_band: strong
modules:
  billing:
    paths: ["internal/billing/**"]
`
	out := string(initcfg.MigrateToV2([]byte(src)).Output)
	gate := strings.Index(out, "    distributed_monolith:")
	modules := strings.Index(out, "modules:")
	if gate < 0 || modules < 0 {
		t.Fatalf("output missing gate stanza or modules block:\n%s", out)
	}
	if gate > modules {
		t.Errorf("replacement stanza landed after modules: — it must stay inside the gate block:\n%s", out)
	}
}

// TestMigrateToV2_KeepsAnAuthoredStanza pins the hybrid case: a config that
// already declares distributed_monolith (perhaps a partial hand-migration)
// loses only the retired keys. Splicing a second stanza in would produce a
// duplicate YAML key, which the decoder rejects — a migration that leaves the
// file unloadable is worse than one that does nothing.
func TestMigrateToV2_KeepsAnAuthoredStanza(t *testing.T) {
	const hybrid = `version: 1
coupling:
  gate:
    min_band: strong
    distributed_monolith:
      mode: fail
      max_new_seams: 3
`
	got := initcfg.MigrateToV2([]byte(hybrid))
	out := string(got.Output)

	if strings.Count(out, "distributed_monolith:") != 1 {
		t.Errorf("migration produced a duplicate stanza:\n%s", out)
	}
	if !strings.Contains(out, "mode: fail") || !strings.Contains(out, "max_new_seams: 3") {
		t.Errorf("migration overwrote the author's own policy:\n%s", out)
	}
	if strings.Contains(out, "min_band") {
		t.Errorf("migration kept the retired key:\n%s", out)
	}
	if second := initcfg.MigrateToV2(got.Output); second.Changed() {
		t.Errorf("second pass reports %q, want already_current", second.Status)
	}
}

// TestMigrateToV2_KeepsAnAuthoredFlowStanza is the flow-style twin of the test
// above. The stanza guard used to require a bare `distributed_monolith:` on its
// own line, so an inline mapping went unseen and the migration spliced a second
// copy of the key into the same YAML mapping — an unloadable file, and the gate
// mode decided by duplicate-key resolution rather than by the author.
func TestMigrateToV2_KeepsAnAuthoredFlowStanza(t *testing.T) {
	const hybrid = `version: 1
coupling:
  gate:
    min_band: strong
    distributed_monolith: {mode: fail, max_new_seams: 3}
`
	got := initcfg.MigrateToV2([]byte(hybrid))
	out := string(got.Output)

	if strings.Count(out, "distributed_monolith:") != 1 {
		t.Errorf("migration produced a duplicate stanza:\n%s", out)
	}
	if !strings.Contains(out, "mode: fail") {
		t.Errorf("migration overwrote the author's own policy:\n%s", out)
	}
	if strings.Contains(out, "min_band") {
		t.Errorf("migration kept the retired key:\n%s", out)
	}
}

// TestMigrateToV2_RemovesAValuelessRetiredKey pins that a bare `min_band:` is
// still the retired key. Leaving it behind ships a file stamped v2 that the
// current schema still rejects — a migration whose only outcome is a
// dead end.
func TestMigrateToV2_RemovesAValuelessRetiredKey(t *testing.T) {
	const src = `version: 1
coupling:
  gate:
    min_band:
`
	got := initcfg.MigrateToV2([]byte(src))
	if strings.Contains(string(got.Output), "min_band") {
		t.Errorf("migration kept the valueless retired key:\n%s", got.Output)
	}
	if second := initcfg.MigrateToV2(got.Output); second.Changed() {
		t.Errorf("second pass reports %q, want already_current", second.Status)
	}
}

// TestMigrateToV2_RetiredKeysAtMixedIndentDoNotPanic pins the slice bound that
// used to blow up. A later retired key at a SHALLOWER indent lets the
// comment-drop pass pop lines from below the recorded insert position, so the
// splice index ran past the end of the kept slice. The input is valid YAML and
// reachable straight from `config update --migration-only --apply`, so the user
// got a Go stack trace instead of exit 3.
func TestMigrateToV2_RetiredKeysAtMixedIndentDoNotPanic(t *testing.T) {
	const src = `version: 1
coupling:
  gate:
  # documents min_band
  # second comment line
    min_band: strong
  max_drop: 5
`
	got := initcfg.MigrateToV2([]byte(src))
	out := string(got.Output)
	if strings.Contains(out, "min_band") || strings.Contains(out, "max_drop") {
		t.Errorf("migration kept a retired key:\n%s", out)
	}
	if !strings.Contains(out, "distributed_monolith:") {
		t.Errorf("migration dropped the replacement stanza:\n%s", out)
	}
}

// TestMigrateToV2_NeverDowngradesANewerSchema pins the direction of the version
// edit. A file declaring a schema this build does not know is "upgrade
// archfit", which validateSchemaVersion already says; rewriting it down to the
// target would answer a question the migration was never asked.
// TestMigrateToV2_RefusesAnUnversionedFile pins the refusal. A file with no
// root `version:` loads under no archfit schema (v1 required `version > 0`
// too), and the migration cannot mechanically supply one: prepending
// `version: 2` above a `---` marker splices a second YAML document, and the
// loader would then validate the two-line first document while dropping the
// config the author wrote. Report it; never guess.
func TestMigrateToV2_RefusesAnUnversionedFile(t *testing.T) {
	tests := []struct {
		name string
		src  string
	}{
		{name: "no version key at all", src: "modules:\n  a:\n    paths: [\"a/**\"]\n"},
		{
			name: "no version key beside a retired knob",
			src:  "coupling:\n  gate:\n    min_band: strong\n",
		},
		{
			name: "a document marker the transform must not prepend above",
			src:  "---\nmodules:\n  a:\n    paths: [\"a/**\"]\n",
		},
		{name: "a nested version does not count as the root one", src: "modules:\n  a:\n    version: 1\n"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := initcfg.MigrateToV2([]byte(tc.src))
			if got.Status != initcfg.MigrationUnversioned {
				t.Errorf("status = %q, want %q", got.Status, initcfg.MigrationUnversioned)
			}
			if got.Changed() {
				t.Errorf("an unversioned file reported a migration: %+v", got.Changes)
			}
			if string(got.Output) != tc.src {
				t.Errorf("an unversioned file was rewritten:\n%s", got.Output)
			}
		})
	}
}

func TestMigrateToV2_NeverDowngradesANewerSchema(t *testing.T) {
	const src = `version: 3
coupling:
  gate:
    min_band: strong
`
	got := initcfg.MigrateToV2([]byte(src))
	if !strings.Contains(string(got.Output), "version: 3") {
		t.Errorf("migration rewrote a newer schema version:\n%s", got.Output)
	}
	if got.FromVersion != 3 {
		t.Errorf("FromVersion = %d, want 3", got.FromVersion)
	}
}
