// Package initcfg — Task 0: goccy v1.19.2 capability spike.
//
// These are characterization tests that pin the goccy behaviors the
// source patcher (Task 7) will rely on. They are read-only: no production
// code is imported from internal/config or internal/llm.
//
// What this file proves (or refutes) for the patcher design:
//
//  1. ParseBytes + ParseComments preserves comments on ast.File.String().
//  2. ast.File.String() is NOT byte-identical to input (whitespace/quote
//     differences exist), which is why the patcher must use line-splice on
//     the original bytes rather than re-serialising through goccy.
//  3. MappingValueNode.Replace() (node replacement) loses comments inside
//     the replaced subtree — another justification for line-splice.
//  4. Token.Position.Line / .Column are 1-based and expose the source
//     location of any key, so the patcher can locate module ranges.
//  5. Top-level keys (layers:, modules:, languages:, rules:) are reachable as
//     MappingValueNode children of the document body.
package initcfg

import (
	"strings"
	"testing"

	"github.com/goccy/go-yaml/ast"
	"github.com/goccy/go-yaml/parser"
)

// Probe-local key constants (goconst requires constants for repeated literals).
const (
	probeKeyModules   = "modules"
	probeKeyLayers    = "layers"
	probeKeyPaths     = "paths"
	probeKeyVersion   = "version"
	probeKeyLanguages = "languages"
	probeKeyRules     = "rules"
	testClassify      = "classify"
)

// sampleArchfitYAML is a minimal .archfit.yaml used across the probes.
// It intentionally contains head comments, inline comments, and a
// commented-inert field so we can observe how goccy preserves them.
const sampleArchfitYAML = `# Generated by archfit init — TODO: review
version: 2

# coupling advisory floor
coupling:
  min_severity: medium

languages:
  go:
    enabled: true
# Off-gate LLM — never used by analyze
# ai:
#   provider: anthropic

layers:
  - model
  - core
  - adapter

modules:
  classify:
    paths:
      - "internal/classify/**"
    layer: core
    # subdomain: core      # llm-suggested
  extract:
    paths:
      - "internal/extract/**"
    layer: adapter

rules:
  - id: no-forbidden-deps
    type: forbidden_dependency
    gate: warn
`

// ---------------------------------------------------------------------------
// Probe 1: ParseComments preserves untouched comments on File.String()
// ---------------------------------------------------------------------------

// TestProbe_ParseComments_PreservesComments verifies that when ParseComments
// mode is used, comments in the input survive a round-trip through
// ast.File.String(). This is the prerequisite for using goccy to locate
// nodes while leaving the original bytes (comment-rich) intact.
func TestProbe_ParseComments_PreservesComments(t *testing.T) {
	f, err := parser.ParseBytes([]byte(sampleArchfitYAML), parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	out := f.String()

	// Key comments that must survive.
	mustContain := []string{
		"Generated by archfit init",
		"coupling advisory floor",
		"Off-gate LLM",
		"llm-suggested",
	}
	for _, want := range mustContain {
		if !strings.Contains(out, want) {
			t.Errorf("comment lost after File.String(): %q not found in output\n---\n%s", want, out)
		}
	}
}

// TestProbe_ParseNoComments_DropsComments verifies the contrast: without
// ParseComments the AST drops all comment nodes, so File.String() loses them.
func TestProbe_ParseNoComments_DropsComments(t *testing.T) {
	f, err := parser.ParseBytes([]byte(sampleArchfitYAML), 0)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	out := f.String()

	// Without ParseComments, these comments should be absent.
	shouldBeAbsent := []string{
		"Generated by archfit init",
		"coupling advisory floor",
	}
	for _, want := range shouldBeAbsent {
		if strings.Contains(out, want) {
			t.Logf("NOTE: comment %q survived even without ParseComments — record actual behavior", want)
		}
	}
	// Document the actual behavior regardless (characterization, not assertion).
	t.Logf("File.String() without ParseComments len=%d", len(out))
}

// ---------------------------------------------------------------------------
// Probe 2: ast.File.String() is NOT byte-identical to input
// ---------------------------------------------------------------------------

// TestProbe_FileString_NotByteIdentical confirms that goccy's serialiser
// produces output that differs from the original source. This justifies the
// line-splice design: the patcher mutates the *original bytes* via line
// ranges located by the AST, instead of re-serialising through goccy.
func TestProbe_FileString_NotByteIdentical(t *testing.T) {
	src := []byte(sampleArchfitYAML)
	f, err := parser.ParseBytes(src, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	out := f.String()

	if string(src) == out {
		// If goccy ever achieves byte-identity this would change our design.
		t.Log("SURPRISING: File.String() IS byte-identical to input — re-evaluate line-splice assumption")
	} else {
		t.Logf("CONFIRMED: File.String() differs from input (expected). input=%d bytes, output=%d bytes",
			len(src), len(out))
	}
	// Characterization: always record a diff excerpt.
	if string(src) != out {
		srcLines := strings.Split(string(src), "\n")
		outLines := strings.Split(out, "\n")
		// Find and report first differing line.
		for i := 0; i < len(srcLines) && i < len(outLines); i++ {
			if srcLines[i] != outLines[i] {
				t.Logf("  first diff at line %d:\n    src: %q\n    out: %q", i+1, srcLines[i], outLines[i])
				break
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Probe 3: MappingValueNode.Replace drops comments in the replaced subtree
// ---------------------------------------------------------------------------

// TestProbe_NodeReplace_DropsComments demonstrates that replacing a node's
// value via MappingValueNode.Replace loses comments that were attached to the
// replaced subtree. This is a key justification for the line-splice patcher.
func TestProbe_NodeReplace_DropsComments(t *testing.T) {
	// A mapping with a comment inside the value subtree.
	src := probeKeyModules + `:\n  classify:\n    paths:\n      - "internal/classify/**"\n    layer: core\n    # llm-suggested — review\n`
	// Use a literal string to avoid \n in the constant.
	srcLit := "modules:\n  classify:\n    paths:\n      - \"internal/classify/**\"\n    layer: core\n    # llm-suggested — review\n"
	_ = src // suppress unused warning from the constant reference above
	f, err := parser.ParseBytes([]byte(srcLit), parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	// Navigate to modules → classify and replace its value with a new mapping.
	body, ok := f.Docs[0].Body.(*ast.MappingNode)
	if !ok {
		t.Fatalf("body is %T, want *ast.MappingNode", f.Docs[0].Body)
	}

	// Find the modules key.
	var modulesMV *ast.MappingValueNode
	for _, mv := range body.Values {
		if mv.Key.(*ast.StringNode).Value == probeKeyModules {
			modulesMV = mv
			break
		}
	}
	if modulesMV == nil {
		t.Fatal(probeKeyModules + " key not found")
	}

	// Replace the value with a simple mapping (simulating a node-level mutation).
	newDoc, err := parser.ParseBytes([]byte("  classify:\n    paths:\n      - \"new/**\"\n    layer: core\n"), parser.ParseComments)
	if err != nil {
		t.Fatalf("parse replacement: %v", err)
	}
	newNode := newDoc.Docs[0].Body

	if err := modulesMV.Replace(newNode); err != nil {
		t.Fatalf("Replace: %v", err)
	}

	out := f.String()

	// The "llm-suggested" comment was inside classify's subtree.
	// After replacement it should be gone.
	if strings.Contains(out, "llm-suggested") {
		t.Log("NOTE: comment survived node replacement — contrary to expectation; record actual behavior")
	} else {
		t.Log("CONFIRMED: Replace() loses comments inside the replaced subtree (expected)")
	}
	t.Logf("Output after Replace:\n%s", out)
}

// ---------------------------------------------------------------------------
// Probe 4: Token positions are 1-based and accurate
// ---------------------------------------------------------------------------

// TestProbe_TokenPosition_OneBased checks that token positions reported by
// goccy are 1-based line/column numbers, allowing the patcher to convert them
// to 0-based byte-slice line indices via (Line - 1).
func TestProbe_TokenPosition_OneBased(t *testing.T) {
	src := []byte(sampleArchfitYAML)
	f, err := parser.ParseBytes(src, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	body, ok := f.Docs[0].Body.(*ast.MappingNode)
	if !ok {
		t.Fatalf("body is %T", f.Docs[0].Body)
	}

	// Find the layers key and record its token position.
	var layersLine, layersCol int
	for _, mv := range body.Values {
		if mv.Key.(*ast.StringNode).Value == probeKeyLayers {
			pos := mv.Key.GetToken().Position
			layersLine = pos.Line
			layersCol = pos.Column
			t.Logf("layers: token position = line %d, col %d", layersLine, layersCol)
			break
		}
	}

	if layersLine == 0 {
		t.Fatal(probeKeyLayers + " key not found")
	}

	// Verify 1-based: the actual text at (layersLine-1) in source must start "layers".
	lines := strings.Split(string(src), "\n")
	if layersLine-1 >= len(lines) {
		t.Fatalf("layersLine=%d is out of range (only %d lines)", layersLine, len(lines))
	}
	actualLine := lines[layersLine-1]
	if !strings.HasPrefix(strings.TrimSpace(actualLine), probeKeyLayers) {
		t.Errorf("position mismatch: line %d = %q, want prefix %q", layersLine, actualLine, probeKeyLayers)
	}
	if layersCol != 1 {
		t.Logf("NOTE: layers column = %d (expected 1 for a top-level key)", layersCol)
	}
	t.Logf("CONFIRMED: token position is 1-based (line %d → %q)", layersLine, actualLine)
}

// TestProbe_ModuleTokenPositions checks that module stanza keys inside the
// modules: block expose correct line positions — this is what the patcher uses
// to locate the range of a named module.
func TestProbe_ModuleTokenPositions(t *testing.T) {
	src := []byte(sampleArchfitYAML)
	f, err := parser.ParseBytes(src, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	body, ok := f.Docs[0].Body.(*ast.MappingNode)
	if !ok {
		t.Fatalf("body is %T", f.Docs[0].Body)
	}

	// Navigate to modules: block.
	var modulesMV *ast.MappingValueNode
	for _, mv := range body.Values {
		if mv.Key.(*ast.StringNode).Value == probeKeyModules {
			modulesMV = mv
			break
		}
	}
	if modulesMV == nil {
		t.Fatal(probeKeyModules + " key not found")
	}

	modulesMap, ok := modulesMV.Value.(*ast.MappingNode)
	if !ok {
		t.Fatalf("modules value is %T, want *ast.MappingNode", modulesMV.Value)
	}

	lines := strings.Split(string(src), "\n")

	for _, mv := range modulesMap.Values {
		name := mv.Key.(*ast.StringNode).Value
		pos := mv.Key.GetToken().Position
		t.Logf("module %q: line=%d col=%d", name, pos.Line, pos.Column)

		// Verify the 1-based position maps to the correct source line.
		if pos.Line-1 >= len(lines) {
			t.Errorf("module %q: line %d out of range", name, pos.Line)
			continue
		}
		actualLine := lines[pos.Line-1]
		if !strings.Contains(actualLine, name+":") {
			t.Errorf("module %q: source line %d = %q, expected %q:", name, pos.Line, actualLine, name)
		}

		// Verify value (the module body) has a token too.
		if mv.Value != nil && mv.Value.GetToken() != nil {
			vpos := mv.Value.GetToken().Position
			t.Logf("  value token: line=%d col=%d", vpos.Line, vpos.Column)
		}
	}
}

// ---------------------------------------------------------------------------
// Probe 5: Top-level key navigation and layers: sequence access
// ---------------------------------------------------------------------------

// TestProbe_TopLevelKeys_Navigation verifies that top-level YAML keys
// (layers, modules, tools, rules) are accessible as MappingValueNode children
// of the document body MappingNode.
func TestProbe_TopLevelKeys_Navigation(t *testing.T) {
	f, err := parser.ParseBytes([]byte(sampleArchfitYAML), parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	body, ok := f.Docs[0].Body.(*ast.MappingNode)
	if !ok {
		t.Fatalf("body is %T, want *ast.MappingNode", f.Docs[0].Body)
	}

	found := make(map[string]bool)
	for _, mv := range body.Values {
		key := mv.Key.(*ast.StringNode).Value
		found[key] = true
	}

	for _, want := range []string{probeKeyVersion, probeKeyLayers, probeKeyModules, probeKeyLanguages, probeKeyRules} {
		if !found[want] {
			t.Errorf("top-level key %q not found; found keys: %v", want, keysOf(found))
		}
	}
	t.Logf("CONFIRMED: top-level keys accessible via body.Values: %v", keysOf(found))
}

// TestProbe_Layers_SequenceValues reads the layers: sequence and extracts
// string values, confirming the AST path for reading the allowed-layers set.
func TestProbe_Layers_SequenceValues(t *testing.T) {
	f, err := parser.ParseBytes([]byte(sampleArchfitYAML), parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	body := f.Docs[0].Body.(*ast.MappingNode)

	var layers []string
	for _, mv := range body.Values {
		if mv.Key.(*ast.StringNode).Value != probeKeyLayers {
			continue
		}
		seq, ok := mv.Value.(*ast.SequenceNode)
		if !ok {
			t.Fatalf("layers value is %T, want *ast.SequenceNode", mv.Value)
		}
		for _, entry := range seq.Values {
			s, ok := entry.(*ast.StringNode)
			if !ok {
				t.Logf("layers entry is %T (not *ast.StringNode)", entry)
				continue
			}
			layers = append(layers, s.Value)
		}
		break
	}

	want := []string{layerModel, layerCore, layerAdapter}
	if len(layers) != len(want) {
		t.Fatalf("layers = %v, want %v", layers, want)
	}
	for i, v := range layers {
		if v != want[i] {
			t.Errorf("layers[%d] = %q, want %q", i, v, want[i])
		}
	}
	t.Logf("CONFIRMED: layers sequence values = %v", layers)
}

// TestProbe_PathsBlock_LineRange verifies that the patcher can locate the
// start and end lines of a module's paths: block by reading the key token
// position of "paths" and its sequence entries.
func TestProbe_PathsBlock_LineRange(t *testing.T) {
	src := []byte(sampleArchfitYAML)
	f, err := parser.ParseBytes(src, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	body := f.Docs[0].Body.(*ast.MappingNode)

	var classifyMV *ast.MappingValueNode
	for _, mv := range body.Values {
		if mv.Key.(*ast.StringNode).Value != probeKeyModules {
			continue
		}
		for _, modMV := range mv.Value.(*ast.MappingNode).Values {
			if modMV.Key.(*ast.StringNode).Value == testClassify {
				classifyMV = modMV
				break
			}
		}
		break
	}
	if classifyMV == nil {
		t.Fatal(testClassify + " module not found")
	}

	classifyBody, ok := classifyMV.Value.(*ast.MappingNode)
	if !ok {
		t.Fatalf("classify value is %T", classifyMV.Value)
	}

	var pathsMV *ast.MappingValueNode
	for _, mv := range classifyBody.Values {
		if mv.Key.(*ast.StringNode).Value == probeKeyPaths {
			pathsMV = mv
			break
		}
	}
	if pathsMV == nil {
		t.Fatal(probeKeyPaths + " key not found in classify")
	}

	pathsKeyLine := pathsMV.Key.GetToken().Position.Line
	t.Logf("classify.paths key at line %d", pathsKeyLine)

	// The sequence entries have their own token positions.
	seq := pathsMV.Value.(*ast.SequenceNode)
	if len(seq.Values) == 0 {
		t.Fatal("paths sequence is empty")
	}
	for i, entry := range seq.Values {
		pos := entry.GetToken().Position
		t.Logf("  paths[%d] at line %d col %d: %s", i, pos.Line, pos.Column, entry.(*ast.StringNode).Value)
	}

	lines := strings.Split(string(src), "\n")
	if pathsKeyLine-1 >= len(lines) {
		t.Fatalf("pathsKeyLine %d out of range", pathsKeyLine)
	}
	if !strings.Contains(lines[pathsKeyLine-1], probeKeyPaths+":") {
		t.Errorf("line %d = %q, expected %q", pathsKeyLine, lines[pathsKeyLine-1], probeKeyPaths+":")
	}
	t.Logf("CONFIRMED: paths: key correctly located at line %d", pathsKeyLine)
}

// ---------------------------------------------------------------------------
// Probe 6: Module line range — key start to next sibling start
// ---------------------------------------------------------------------------

// TestProbe_ModuleLineRange_AdjacentSiblings verifies the core range-finding
// strategy: a module's line range runs from its key token line (inclusive)
// to the next sibling's key token line (exclusive). This is how the patcher
// locates the byte slice to replace or comment.
func TestProbe_ModuleLineRange_AdjacentSiblings(t *testing.T) {
	src := []byte(sampleArchfitYAML)
	f, err := parser.ParseBytes(src, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseBytes: %v", err)
	}

	body := f.Docs[0].Body.(*ast.MappingNode)

	var modulesMap *ast.MappingNode
	for _, mv := range body.Values {
		if mv.Key.(*ast.StringNode).Value == probeKeyModules {
			modulesMap = mv.Value.(*ast.MappingNode)
			break
		}
	}
	if modulesMap == nil {
		t.Fatal(probeKeyModules + " not found")
	}

	type modRange struct {
		name      string
		startLine int // key token line (1-based)
	}
	ranges := make([]modRange, 0, len(modulesMap.Values))
	for _, mv := range modulesMap.Values {
		ranges = append(ranges, modRange{
			name:      mv.Key.(*ast.StringNode).Value,
			startLine: mv.Key.GetToken().Position.Line,
		})
	}

	if len(ranges) < 2 {
		t.Fatalf("expected ≥2 modules, got %d", len(ranges))
	}

	// classify ends at (extract.startLine - 1).
	classify := ranges[0]
	extract := ranges[1]

	t.Logf("classify starts at line %d, extract at line %d", classify.startLine, extract.startLine)

	lines := strings.Split(string(src), "\n")
	if classify.startLine-1 >= len(lines) || extract.startLine-1 >= len(lines) {
		t.Fatal("line range out of bounds")
	}
	t.Logf("classify range: lines[%d..%d)", classify.startLine-1, extract.startLine-1)
	for i := classify.startLine - 1; i < extract.startLine-1; i++ {
		t.Logf("  [%d] %s", i+1, lines[i])
	}

	// Sanity: the range must include "classify:" and its body, but not "extract:".
	rangeText := strings.Join(lines[classify.startLine-1:extract.startLine-1], "\n")
	if !strings.Contains(rangeText, testClassify+":") {
		t.Errorf("range does not contain %q:\n%s", testClassify+":", rangeText)
	}
	if strings.Contains(rangeText, "extract:") {
		t.Errorf("range unexpectedly contains 'extract:':\n%s", rangeText)
	}
	t.Log("CONFIRMED: sibling-key line range correctly isolates a module stanza")
}

// keysOf returns the keys of a bool map for logging.
func keysOf(m map[string]bool) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	return ks
}
