// Package initcfg — tests for ApplyEdits (Task 7 source patcher).
package initcfg

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/alexei-led/archfit/internal/config"
)

// testMyMod is a placeholder module name used in insertion-location tests.
const (
	testMyMod     = "mymod"
	testMyModPath = "pkg/mymod/**"
)

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

// fullFixture is the primary test fixture: has comments, rules, exceptions, two modules.
const fullFixture = `# Generated by archfit init
version: 1

bc_advisory_min_severity: medium

tools:
  go:
    enabled: "on"
  # comment in tools

layers:
  - model
  - core
  - adapter

# modules section comment
modules:
  # head comment for classify
  classify:
    paths:
      - "internal/classify/**"
    layer: core
  extract:
    paths:
      - "internal/extract/**"
    layer: adapter

rules:
  - id: no-forbidden-deps
    type: forbidden_dependency
    gate: warn

exceptions:
  - rule: no-forbidden-deps
    from: classify
    to: extract
    reason: legacy
`

// noModulesWithLayers has layers: but no modules: section.
const noModulesWithLayers = `version: 1

layers:
  - model
  - core
  - adapter

rules:
  - id: no-forbidden-deps
    type: forbidden_dependency
    gate: warn
`

// noModulesWithTools has tools: but no layers:, no modules:.
const noModulesWithTools = `version: 1

tools:
  go:
    enabled: "on"

rules:
  - id: no-forbidden-deps
    type: forbidden_dependency
    gate: warn
`

// noModulesRulesOnly has only rules: (no layers, no tools, no modules).
const noModulesRulesOnly = `version: 1

rules:
  - id: no-forbidden-deps
    type: forbidden_dependency
    gate: warn
`

// noModulesVersionOnly has only version: (no other top-level keys).
const noModulesVersionOnly = `version: 1
`

// flowModules has a flow-style modules: {} which must be rejected.
const flowModules = `version: 1
modules: {}
`

// flowPaths has a flow-style paths: [...] inside a module.
const flowPaths = `version: 1

layers:
  - core

modules:
  classify:
    paths: ["internal/classify/**"]
    layer: core
`

// moduleWithNoPaths has a module with no paths: key.
const moduleWithNoPaths = `version: 1

layers:
  - core

modules:
  classify:
    layer: core

rules:
  - id: no-forbidden-deps
    type: forbidden_dependency
    gate: warn
`

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// mustApply applies edits and fatals on error.
func mustApply(t *testing.T, src string, edits ...Edit) string {
	t.Helper()
	out, err := ApplyEdits([]byte(src), edits)
	if err != nil {
		t.Fatalf("ApplyEdits: %v", err)
	}
	return string(out)
}

// mustRoundTrip writes yaml to a temp file and calls config.Load; fatals on error.
func mustRoundTrip(t *testing.T, yamlContent string) config.Config {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, ".archfit.yaml")
	if err := os.WriteFile(path, []byte(yamlContent), 0o600); err != nil {
		t.Fatalf("write temp: %v", err)
	}
	cfg, err := config.Load(context.Background(), path)
	if err != nil {
		t.Fatalf("config.Load round-trip failed: %v\n---yaml---\n%s", err, yamlContent)
	}
	return cfg
}

// assertContains fails if want is not in got.
func assertContains(t *testing.T, got, want string) {
	t.Helper()
	if !strings.Contains(got, want) {
		t.Errorf("output missing %q\n--- got ---\n%s", want, got)
	}
}

// assertNotContains fails if unwanted is in got.
func assertNotContains(t *testing.T, got, unwanted string) {
	t.Helper()
	if strings.Contains(got, unwanted) {
		t.Errorf("output must not contain %q\n--- got ---\n%s", unwanted, got)
	}
}

// ---------------------------------------------------------------------------
// Test: AddModule into config with existing comments and rules
// ---------------------------------------------------------------------------

func TestApplyEdits_AddModule_CommentsAndRulesIntact(t *testing.T) {
	ed := AddModuleEdit{
		Def: ModuleDef{
			Name:  layerModel,
			Paths: []string{"internal/model/**"},
			Layer: layerModel,
		},
	}
	out := mustApply(t, fullFixture, ed)

	// New module present.
	assertContains(t, out, "model:")
	assertContains(t, out, `"internal/model/**"`)

	// Original modules untouched.
	assertContains(t, out, "classify:")
	assertContains(t, out, "extract:")

	// Comments preserved.
	assertContains(t, out, "Generated by archfit init")
	assertContains(t, out, "head comment for classify")
	assertContains(t, out, "modules section comment")
	assertContains(t, out, "comment in tools")

	// rules and exceptions preserved.
	assertContains(t, out, "no-forbidden-deps")
	assertContains(t, out, "exceptions:")
	assertContains(t, out, "reason: legacy")

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: AddModule into config with NO modules: block — insertion locations
// ---------------------------------------------------------------------------

func TestApplyEdits_AddModule_NoModulesSection_AfterLayers(t *testing.T) {
	ed := AddModuleEdit{
		Def: ModuleDef{Name: testMyMod, Paths: []string{testMyModPath}, Layer: layerCore},
	}
	out := mustApply(t, noModulesWithLayers, ed)

	assertContains(t, out, "modules:")
	assertContains(t, out, testMyMod+":")
	assertContains(t, out, `"`+testMyModPath+`"`)
	assertContains(t, out, "rules:") // rules still present

	// modules: must appear BEFORE rules:
	modIdx := strings.Index(out, "modules:")
	rulesIdx := strings.Index(out, "rules:")
	if modIdx >= rulesIdx {
		t.Errorf("modules: (%d) should appear before rules: (%d)", modIdx, rulesIdx)
	}
	// And AFTER layers:
	layersIdx := strings.Index(out, "layers:")
	if modIdx <= layersIdx {
		t.Errorf("modules: (%d) should appear after layers: (%d)", modIdx, layersIdx)
	}

	mustRoundTrip(t, out)
}

func TestApplyEdits_AddModule_NoModulesSection_AfterTools(t *testing.T) {
	ed := AddModuleEdit{
		Def: ModuleDef{Name: testMyMod, Paths: []string{testMyModPath}, Layer: layerCore},
	}
	out := mustApply(t, noModulesWithTools, ed)

	assertContains(t, out, "modules:")
	assertContains(t, out, testMyMod+":")
	assertContains(t, out, "rules:")

	toolsIdx := strings.Index(out, "tools:")
	modIdx := strings.Index(out, "modules:")
	rulesIdx := strings.Index(out, "rules:")
	if modIdx <= toolsIdx {
		t.Errorf("modules: (%d) should appear after tools: (%d)", modIdx, toolsIdx)
	}
	if modIdx >= rulesIdx {
		t.Errorf("modules: (%d) should appear before rules: (%d)", modIdx, rulesIdx)
	}

	mustRoundTrip(t, out)
}

func TestApplyEdits_AddModule_NoModulesSection_BeforeRules(t *testing.T) {
	ed := AddModuleEdit{
		Def: ModuleDef{Name: testMyMod, Paths: []string{testMyModPath}, Layer: layerCore},
	}
	out := mustApply(t, noModulesRulesOnly, ed)

	assertContains(t, out, "modules:")
	assertContains(t, out, testMyMod+":")

	modIdx := strings.Index(out, "modules:")
	rulesIdx := strings.Index(out, "rules:")
	if modIdx >= rulesIdx {
		t.Errorf("modules: (%d) should appear before rules: (%d)", modIdx, rulesIdx)
	}

	mustRoundTrip(t, out)
}

func TestApplyEdits_AddModule_NoModulesSection_AppendEOF(t *testing.T) {
	ed := AddModuleEdit{
		Def: ModuleDef{Name: testMyMod, Paths: []string{testMyModPath}, Layer: layerCore},
	}
	out := mustApply(t, noModulesVersionOnly, ed)

	assertContains(t, out, "modules:")
	assertContains(t, out, testMyMod+":")

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: AddModule is NO-OP if module already exists live
// ---------------------------------------------------------------------------

func TestApplyEdits_AddModule_NoOpIfExists(t *testing.T) {
	ed := AddModuleEdit{
		Def: ModuleDef{Name: testClassify, Paths: []string{testClassifyPath}, Layer: layerCore},
	}
	out := mustApply(t, fullFixture, ed)

	// Output must be identical to input (no extra classify: stanza added).
	if strings.Count(out, "classify:") != strings.Count(fullFixture, "classify:") {
		t.Errorf("AddModule should be no-op: classify: count changed\n--- out ---\n%s", out)
	}

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: SetModuleFields coalesces multiple absent fields into one block
// ---------------------------------------------------------------------------

func TestApplyEdits_SetModuleFields_CoalesceMultiple(t *testing.T) {
	// classify has layer: core but no subdomain or volatility.
	ed := SetModuleFieldsEdit{
		Module: testClassify,
		Fields: map[ModuleField]string{
			FieldSubdomain:  layerCore,
			FieldVolatility: "low",
			FieldLayer:      layerCore, // already present — should be skipped
		},
	}
	out := mustApply(t, fullFixture, ed)

	assertContains(t, out, "subdomain: core")
	assertContains(t, out, "volatility: low")

	// Canonical order: subdomain before volatility.
	subIdx := strings.Index(out, "subdomain:")
	volIdx := strings.Index(out, "volatility:")
	if subIdx >= volIdx {
		t.Errorf("subdomain: (%d) should appear before volatility: (%d)", subIdx, volIdx)
	}

	// layer: core already present — should not be duplicated.
	if strings.Count(out, "layer: core") != 1 {
		t.Errorf("layer: core should appear exactly once, got %d", strings.Count(out, "layer: core"))
	}

	// Original content preserved.
	assertContains(t, out, "head comment for classify")
	assertContains(t, out, "no-forbidden-deps")

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: SetModuleFields skips out-of-set Layer
// ---------------------------------------------------------------------------

func TestApplyEdits_SetModuleFields_SkipsOutOfSetLayer(t *testing.T) {
	// layers: has [model, core, adapter]; "presentation" is not in the set.
	ed := SetModuleFieldsEdit{
		Module: testClassify,
		Fields: map[ModuleField]string{
			FieldSubdomain: testGeneric,
			FieldLayer:     "presentation", // out of set
		},
	}
	out := mustApply(t, fullFixture, ed)

	assertContains(t, out, "subdomain: generic")
	assertNotContains(t, out, "presentation") // must not appear

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: SetModuleFields on missing module returns error
// ---------------------------------------------------------------------------

func TestApplyEdits_SetModuleFields_MissingModuleError(t *testing.T) {
	ed := SetModuleFieldsEdit{
		Module: testNonexistent,
		Fields: map[ModuleField]string{FieldSubdomain: layerCore},
	}
	_, err := ApplyEdits([]byte(fullFixture), []Edit{ed})
	if err == nil {
		t.Fatal("expected error for missing module, got nil")
	}
	assertContains(t, err.Error(), testNonexistent)
}

// ---------------------------------------------------------------------------
// Test: UpdateModulePaths replaces existing paths block
// ---------------------------------------------------------------------------

func TestApplyEdits_UpdateModulePaths_ReplacesExisting(t *testing.T) {
	ed := UpdateModulePathsEdit{
		Module: testClassify,
		Paths:  []string{testClassifyPath, "internal/classify/extra/**"},
	}
	out := mustApply(t, fullFixture, ed)

	assertContains(t, out, `"internal/classify/**"`)
	assertContains(t, out, `"internal/classify/extra/**"`)

	// extract unchanged.
	assertContains(t, out, `"internal/extract/**"`)

	// Comments preserved.
	assertContains(t, out, "head comment for classify")

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: UpdateModulePaths into stanza with no paths:
// ---------------------------------------------------------------------------

func TestApplyEdits_UpdateModulePaths_NoPaths_Inserts(t *testing.T) {
	ed := UpdateModulePathsEdit{
		Module: testClassify,
		Paths:  []string{testClassifyPath},
	}
	out := mustApply(t, moduleWithNoPaths, ed)

	assertContains(t, out, "paths:")
	assertContains(t, out, `"internal/classify/**"`)

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: UpdateModulePaths on missing module returns error
// ---------------------------------------------------------------------------

func TestApplyEdits_UpdateModulePaths_MissingModuleError(t *testing.T) {
	ed := UpdateModulePathsEdit{
		Module: testNonexistent,
		Paths:  []string{"x/**"},
	}
	_, err := ApplyEdits([]byte(fullFixture), []Edit{ed})
	if err == nil {
		t.Fatal("expected error for missing module, got nil")
	}
}

// ---------------------------------------------------------------------------
// Test: Reject flow-style paths: [...]
// ---------------------------------------------------------------------------

func TestApplyEdits_RejectFlowPaths(t *testing.T) {
	ed := UpdateModulePathsEdit{
		Module: testClassify,
		Paths:  []string{testClassifyPath},
	}
	_, err := ApplyEdits([]byte(flowPaths), []Edit{ed})
	if err == nil {
		t.Fatal("expected error for flow-style paths:, got nil")
	}
	assertContains(t, err.Error(), "flow-style")
}

// ---------------------------------------------------------------------------
// Test: Reject flow-style modules: {}
// ---------------------------------------------------------------------------

func TestApplyEdits_RejectFlowModules(t *testing.T) {
	ed := AddModuleEdit{
		Def: ModuleDef{Name: "mymod", Paths: []string{"pkg/**"}, Layer: layerCore},
	}
	_, err := ApplyEdits([]byte(flowModules), []Edit{ed})
	if err == nil {
		t.Fatal("expected error for flow-style modules: {}, got nil")
	}
	assertContains(t, err.Error(), "flow-style")
}

// ---------------------------------------------------------------------------
// Test: CommentModule including head comment
// ---------------------------------------------------------------------------

func TestApplyEdits_CommentModule_IncludesHeadComment(t *testing.T) {
	ed := CommentModuleEdit{
		Module: testClassify,
		Note:   "moved to classifier package",
	}
	out := mustApply(t, fullFixture, ed)

	// Marker present.
	assertContains(t, out, `# archfit: removed module "classify"`)
	assertContains(t, out, "moved to classifier package")

	// Head comment is inside the commented block.
	assertContains(t, out, "# # head comment for classify")

	// The classify: key itself is commented out.
	assertContains(t, out, "# classify:")

	// extract untouched.
	assertContains(t, out, "extract:")
	assertNotContains(t, out, "# extract:")

	// rules and exceptions preserved.
	assertContains(t, out, "no-forbidden-deps")
	assertContains(t, out, "reason: legacy")

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: CommentModule is idempotent (re-apply is no-op)
// ---------------------------------------------------------------------------

func TestApplyEdits_CommentModule_Idempotent(t *testing.T) {
	ed := CommentModuleEdit{
		Module: testClassify,
		Note:   "moved",
	}
	out1 := mustApply(t, fullFixture, ed)

	// Apply again — should be no-op (marker already present).
	out2 := mustApply(t, out1, ed)

	if out1 != out2 {
		t.Errorf("second CommentModule application changed output\n--- out1 ---\n%s\n--- out2 ---\n%s", out1, out2)
	}
}

// ---------------------------------------------------------------------------
// Test: CommentModule on missing module returns error
// ---------------------------------------------------------------------------

func TestApplyEdits_CommentModule_MissingModuleError(t *testing.T) {
	ed := CommentModuleEdit{
		Module: testNonexistent,
		Note:   "gone",
	}
	_, err := ApplyEdits([]byte(fullFixture), []Edit{ed})
	if err == nil {
		t.Fatal("expected error for missing module, got nil")
	}
}

// ---------------------------------------------------------------------------
// Test: AddModule is idempotent (re-apply is no-op)
// ---------------------------------------------------------------------------

func TestApplyEdits_AddModule_Idempotent(t *testing.T) {
	ed := AddModuleEdit{
		Def: ModuleDef{Name: "newmod", Paths: []string{"pkg/newmod/**"}, Layer: layerCore},
	}
	out1 := mustApply(t, fullFixture, ed)

	// Verify it was added.
	assertContains(t, out1, "newmod:")

	// Apply again — the module now exists, so it's a no-op.
	out2 := mustApply(t, out1, ed)

	if out1 != out2 {
		t.Errorf("second AddModule application changed output\n--- out1 ---\n%s\n--- out2 ---\n%s", out1, out2)
	}
}

// ---------------------------------------------------------------------------
// Test: Bottom-up ordering with multiple edits
// ---------------------------------------------------------------------------

func TestApplyEdits_BottomUpOrdering_MultipleEdits(t *testing.T) {
	// Apply: update paths for classify (earlier in file) + update paths for extract (later).
	edits := []Edit{
		UpdateModulePathsEdit{
			Module: testClassify,
			Paths:  []string{testClassifyPath, "internal/classify/v2/**"},
		},
		UpdateModulePathsEdit{
			Module: adapterExtract,
			Paths:  []string{"internal/extract/**", "internal/extract/v2/**"},
		},
	}
	out := mustApply(t, fullFixture, edits...)

	assertContains(t, out, `"internal/classify/v2/**"`)
	assertContains(t, out, `"internal/extract/v2/**"`)

	// Comments and rules preserved.
	assertContains(t, out, "head comment for classify")
	assertContains(t, out, "no-forbidden-deps")

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: sanitizeComment injection guard (via CommentModule note)
// ---------------------------------------------------------------------------

func TestApplyEdits_CommentModule_SanitizesNote(t *testing.T) {
	// A note containing a newline — must not escape into live YAML.
	ed := CommentModuleEdit{
		Module: testClassify,
		Note:   "gone\nvolatility: high",
	}
	out := mustApply(t, fullFixture, ed)

	// The sanitized note must not produce a live volatility: key.
	// After sanitization, \n → ' ', so the note becomes "gone volatility: high"
	// which is inside a comment line starting with #.
	lines := strings.Split(out, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "volatility:") {
			t.Errorf("injection: found live volatility: line not inside a comment: %q", line)
		}
	}

	// marker line exists.
	assertContains(t, out, `# archfit: removed module "classify"`)

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: AddModule with ModuleAnnotation (apply mode)
// ---------------------------------------------------------------------------

func TestApplyEdits_AddModule_WithAnnotation(t *testing.T) {
	ann := &ModuleAnnotation{
		Subdomain:  layerCore,
		Volatility: "low",
		Layer:      layerModel, // in layers: [model, core, adapter]
	}
	ed := AddModuleEdit{
		Def: ModuleDef{Name: "newmod", Paths: []string{"internal/newmod/**"}, Layer: layerModel},
		Ann: ann,
	}
	out := mustApply(t, fullFixture, ed)

	assertContains(t, out, "newmod:")
	assertContains(t, out, "subdomain: core")
	assertContains(t, out, "volatility: low")
	assertContains(t, out, "layer: model")

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: AddModule with out-of-set layer in annotation
// ---------------------------------------------------------------------------

func TestApplyEdits_AddModule_OutOfSetLayerInAnnotation(t *testing.T) {
	ann := &ModuleAnnotation{
		Subdomain:  testGeneric,
		Volatility: "high",
		Layer:      "presentation", // NOT in layers: [model, core, adapter]
	}
	ed := AddModuleEdit{
		Def: ModuleDef{Name: "ui", Paths: []string{"internal/ui/**"}, Layer: layerCore},
		Ann: ann,
	}
	out := mustApply(t, fullFixture, ed)

	assertContains(t, out, "ui:")
	// The out-of-set layer from ann must not appear as a live YAML key.
	assertNotContains(t, out, "\n    layer: presentation\n")
	// The fallback m.Layer (core) is in layers, so it should appear.
	assertContains(t, out, "layer: core")

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: SetModuleFields with no-op fields (all already present)
// ---------------------------------------------------------------------------

func TestApplyEdits_SetModuleFields_AllPresent_NoOp(t *testing.T) {
	// classify already has layer: core; try to set it again + subdomain not present.
	ed := SetModuleFieldsEdit{
		Module: testClassify,
		Fields: map[ModuleField]string{
			FieldLayer: layerCore, // already present
		},
	}
	out := mustApply(t, fullFixture, ed)

	// Should be unchanged (layer already present → skipped).
	if out != fullFixture {
		t.Errorf("expected no-op output, got different result\n--- out ---\n%s", out)
	}
}

// ---------------------------------------------------------------------------
// Test: multiple edits on different modules don't conflict
// ---------------------------------------------------------------------------

func TestApplyEdits_MultipleEdits_NoConflict(t *testing.T) {
	edits := []Edit{
		SetModuleFieldsEdit{
			Module: testClassify,
			Fields: map[ModuleField]string{FieldSubdomain: layerCore},
		},
		SetModuleFieldsEdit{
			Module: adapterExtract,
			Fields: map[ModuleField]string{FieldSubdomain: testGeneric},
		},
	}
	out := mustApply(t, fullFixture, edits...)

	assertContains(t, out, "subdomain: core")
	assertContains(t, out, "subdomain: generic")

	mustRoundTrip(t, out)
}

// ---------------------------------------------------------------------------
// Test: two AddModuleEdits into config with NO modules: block → single header
// ---------------------------------------------------------------------------

func TestApplyEdits_AddModules_TwoIntoEmpty_SingleHeader(t *testing.T) {
	edits := []Edit{
		AddModuleEdit{Def: ModuleDef{Name: testBeta, Paths: []string{"internal/" + testBeta + "/**"}, Layer: layerCore}},
		AddModuleEdit{Def: ModuleDef{Name: testAlpha, Paths: []string{"internal/" + testAlpha + "/**"}, Layer: layerCore}},
	}
	out := mustApply(t, noModulesWithLayers, edits...)

	// Exactly ONE modules: header.
	if cnt := strings.Count(out, "modules:"); cnt != 1 {
		t.Errorf("want exactly 1 'modules:' header, got %d\n--- out ---\n%s", cnt, out)
	}

	// Both modules present.
	assertContains(t, out, testAlpha+":")
	assertContains(t, out, testBeta+":")
	assertContains(t, out, `"internal/`+testAlpha+`/**"`)
	assertContains(t, out, `"internal/`+testBeta+`/**"`)

	// Alphabetical order: alpha before beta.
	alphaIdx := strings.Index(out, testAlpha+":")
	betaIdx := strings.Index(out, testBeta+":")
	if alphaIdx >= betaIdx {
		t.Errorf("alpha: (%d) should appear before beta: (%d)", alphaIdx, betaIdx)
	}

	// Round-trip must succeed (no duplicate mapping keys).
	mustRoundTrip(t, out)
}

// TestApplyEdits_AddModule_SingleIntoEmpty verifies the single-module case still works.
func TestApplyEdits_AddModule_SingleIntoEmpty_StillWorks(t *testing.T) {
	const soloName = "solo"
	ed := AddModuleEdit{
		Def: ModuleDef{Name: soloName, Paths: []string{"internal/" + soloName + "/**"}, Layer: layerCore},
	}
	out := mustApply(t, noModulesWithLayers, ed)

	if cnt := strings.Count(out, "modules:"); cnt != 1 {
		t.Errorf("want exactly 1 'modules:' header, got %d\n--- out ---\n%s", cnt, out)
	}
	assertContains(t, out, soloName+":")
	assertContains(t, out, `"internal/`+soloName+`/**"`)

	mustRoundTrip(t, out)
}
