// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ports

import (
	"context"
	"sync"

	"github.com/alexei-led/archfit/internal/model/diagnostic"
	"github.com/alexei-led/archfit/internal/model/pattern"
	"github.com/alexei-led/archfit/internal/scope"
	"github.com/alexei-led/archfit/internal/view"
)

// Ensure, that PatternProviderMock does implement PatternProvider.
// If this is not the case, regenerate this file with moq.
var _ PatternProvider = &PatternProviderMock{}

// PatternProviderMock is a mock implementation of PatternProvider.
//
//	func TestSomethingThatUsesPatternProvider(t *testing.T) {
//
//		// make and configure a mocked PatternProvider
//		mockedPatternProvider := &PatternProviderMock{
//			FindFunc: func(ctx context.Context, s scope.Scope, c view.PatternConfig) ([]pattern.Match, diagnostic.Coverage, error) {
//				panic("mock out the Find method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//		}
//
//		// use mockedPatternProvider in code that requires PatternProvider
//		// and then make assertions.
//
//	}
type PatternProviderMock struct {
	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, s scope.Scope, c view.PatternConfig) ([]pattern.Match, diagnostic.Coverage, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S scope.Scope
			// C is the c argument value.
			C view.PatternConfig
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
	}
	lockFind sync.RWMutex
	lockName sync.RWMutex
}

// Find calls FindFunc.
func (mock *PatternProviderMock) Find(ctx context.Context, s scope.Scope, c view.PatternConfig) ([]pattern.Match, diagnostic.Coverage, error) {
	if mock.FindFunc == nil {
		panic("PatternProviderMock.FindFunc: method is nil but PatternProvider.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   scope.Scope
		C   view.PatternConfig
	}{
		Ctx: ctx,
		S:   s,
		C:   c,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, s, c)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedPatternProvider.FindCalls())
func (mock *PatternProviderMock) FindCalls() []struct {
	Ctx context.Context
	S   scope.Scope
	C   view.PatternConfig
} {
	var calls []struct {
		Ctx context.Context
		S   scope.Scope
		C   view.PatternConfig
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *PatternProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("PatternProviderMock.NameFunc: method is nil but PatternProvider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedPatternProvider.NameCalls())
func (mock *PatternProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}
