// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ports

import (
	"context"
	"sync"

	"github.com/alexei-led/archfit/internal/model/diagnostic"
	"github.com/alexei-led/archfit/internal/model/symbol"
	"github.com/alexei-led/archfit/internal/scope"
)

// Ensure, that SymbolResolverMock does implement SymbolResolver.
// If this is not the case, regenerate this file with moq.
var _ SymbolResolver = &SymbolResolverMock{}

// SymbolResolverMock is a mock implementation of SymbolResolver.
//
//	func TestSomethingThatUsesSymbolResolver(t *testing.T) {
//
//		// make and configure a mocked SymbolResolver
//		mockedSymbolResolver := &SymbolResolverMock{
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			ResolveFunc: func(ctx context.Context, fromFile string, toPath string) (string, string) {
//				panic("mock out the Resolve method")
//			},
//			StrengthsFunc: func(ctx context.Context, s scope.Scope) (map[string]string, diagnostic.Coverage, error) {
//				panic("mock out the Strengths method")
//			},
//			SymbolsFunc: func(ctx context.Context, s scope.Scope) (symbol.Graph, diagnostic.Coverage, error) {
//				panic("mock out the Symbols method")
//			},
//		}
//
//		// use mockedSymbolResolver in code that requires SymbolResolver
//		// and then make assertions.
//
//	}
type SymbolResolverMock struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(ctx context.Context, fromFile string, toPath string) (string, string)

	// StrengthsFunc mocks the Strengths method.
	StrengthsFunc func(ctx context.Context, s scope.Scope) (map[string]string, diagnostic.Coverage, error)

	// SymbolsFunc mocks the Symbols method.
	SymbolsFunc func(ctx context.Context, s scope.Scope) (symbol.Graph, diagnostic.Coverage, error)

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FromFile is the fromFile argument value.
			FromFile string
			// ToPath is the toPath argument value.
			ToPath string
		}
		// Strengths holds details about calls to the Strengths method.
		Strengths []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S scope.Scope
		}
		// Symbols holds details about calls to the Symbols method.
		Symbols []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S scope.Scope
		}
	}
	lockName      sync.RWMutex
	lockResolve   sync.RWMutex
	lockStrengths sync.RWMutex
	lockSymbols   sync.RWMutex
}

// Name calls NameFunc.
func (mock *SymbolResolverMock) Name() string {
	if mock.NameFunc == nil {
		panic("SymbolResolverMock.NameFunc: method is nil but SymbolResolver.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedSymbolResolver.NameCalls())
func (mock *SymbolResolverMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Resolve calls ResolveFunc.
func (mock *SymbolResolverMock) Resolve(ctx context.Context, fromFile string, toPath string) (string, string) {
	if mock.ResolveFunc == nil {
		panic("SymbolResolverMock.ResolveFunc: method is nil but SymbolResolver.Resolve was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FromFile string
		ToPath   string
	}{
		Ctx:      ctx,
		FromFile: fromFile,
		ToPath:   toPath,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	return mock.ResolveFunc(ctx, fromFile, toPath)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedSymbolResolver.ResolveCalls())
func (mock *SymbolResolverMock) ResolveCalls() []struct {
	Ctx      context.Context
	FromFile string
	ToPath   string
} {
	var calls []struct {
		Ctx      context.Context
		FromFile string
		ToPath   string
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}

// Strengths calls StrengthsFunc.
func (mock *SymbolResolverMock) Strengths(ctx context.Context, s scope.Scope) (map[string]string, diagnostic.Coverage, error) {
	if mock.StrengthsFunc == nil {
		panic("SymbolResolverMock.StrengthsFunc: method is nil but SymbolResolver.Strengths was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   scope.Scope
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockStrengths.Lock()
	mock.calls.Strengths = append(mock.calls.Strengths, callInfo)
	mock.lockStrengths.Unlock()
	return mock.StrengthsFunc(ctx, s)
}

// StrengthsCalls gets all the calls that were made to Strengths.
// Check the length with:
//
//	len(mockedSymbolResolver.StrengthsCalls())
func (mock *SymbolResolverMock) StrengthsCalls() []struct {
	Ctx context.Context
	S   scope.Scope
} {
	var calls []struct {
		Ctx context.Context
		S   scope.Scope
	}
	mock.lockStrengths.RLock()
	calls = mock.calls.Strengths
	mock.lockStrengths.RUnlock()
	return calls
}

// Symbols calls SymbolsFunc.
func (mock *SymbolResolverMock) Symbols(ctx context.Context, s scope.Scope) (symbol.Graph, diagnostic.Coverage, error) {
	if mock.SymbolsFunc == nil {
		panic("SymbolResolverMock.SymbolsFunc: method is nil but SymbolResolver.Symbols was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   scope.Scope
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockSymbols.Lock()
	mock.calls.Symbols = append(mock.calls.Symbols, callInfo)
	mock.lockSymbols.Unlock()
	return mock.SymbolsFunc(ctx, s)
}

// SymbolsCalls gets all the calls that were made to Symbols.
// Check the length with:
//
//	len(mockedSymbolResolver.SymbolsCalls())
func (mock *SymbolResolverMock) SymbolsCalls() []struct {
	Ctx context.Context
	S   scope.Scope
} {
	var calls []struct {
		Ctx context.Context
		S   scope.Scope
	}
	mock.lockSymbols.RLock()
	calls = mock.calls.Symbols
	mock.lockSymbols.RUnlock()
	return calls
}
