// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ports

import (
	"context"
	"sync"

	"github.com/alexei-led/archfit/internal/model/diagnostic"
	"github.com/alexei-led/archfit/internal/scope"
)

// Ensure, that SyntaxProviderMock does implement SyntaxProvider.
// If this is not the case, regenerate this file with moq.
var _ SyntaxProvider = &SyntaxProviderMock{}

// SyntaxProviderMock is a mock implementation of SyntaxProvider.
//
//	func TestSomethingThatUsesSyntaxProvider(t *testing.T) {
//
//		// make and configure a mocked SyntaxProvider
//		mockedSyntaxProvider := &SyntaxProviderMock{
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			SyntaxFunc: func(ctx context.Context, s scope.Scope, langs []string) ([]diagnostic.SyntaxFact, diagnostic.Coverage, error) {
//				panic("mock out the Syntax method")
//			},
//		}
//
//		// use mockedSyntaxProvider in code that requires SyntaxProvider
//		// and then make assertions.
//
//	}
type SyntaxProviderMock struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// SyntaxFunc mocks the Syntax method.
	SyntaxFunc func(ctx context.Context, s scope.Scope, langs []string) ([]diagnostic.SyntaxFact, diagnostic.Coverage, error)

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// Syntax holds details about calls to the Syntax method.
		Syntax []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S scope.Scope
			// Langs is the langs argument value.
			Langs []string
		}
	}
	lockName   sync.RWMutex
	lockSyntax sync.RWMutex
}

// Name calls NameFunc.
func (mock *SyntaxProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("SyntaxProviderMock.NameFunc: method is nil but SyntaxProvider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedSyntaxProvider.NameCalls())
func (mock *SyntaxProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Syntax calls SyntaxFunc.
func (mock *SyntaxProviderMock) Syntax(ctx context.Context, s scope.Scope, langs []string) ([]diagnostic.SyntaxFact, diagnostic.Coverage, error) {
	if mock.SyntaxFunc == nil {
		panic("SyntaxProviderMock.SyntaxFunc: method is nil but SyntaxProvider.Syntax was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		S     scope.Scope
		Langs []string
	}{
		Ctx:   ctx,
		S:     s,
		Langs: langs,
	}
	mock.lockSyntax.Lock()
	mock.calls.Syntax = append(mock.calls.Syntax, callInfo)
	mock.lockSyntax.Unlock()
	return mock.SyntaxFunc(ctx, s, langs)
}

// SyntaxCalls gets all the calls that were made to Syntax.
// Check the length with:
//
//	len(mockedSyntaxProvider.SyntaxCalls())
func (mock *SyntaxProviderMock) SyntaxCalls() []struct {
	Ctx   context.Context
	S     scope.Scope
	Langs []string
} {
	var calls []struct {
		Ctx   context.Context
		S     scope.Scope
		Langs []string
	}
	mock.lockSyntax.RLock()
	calls = mock.calls.Syntax
	mock.lockSyntax.RUnlock()
	return calls
}
