// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package engine

import (
	"context"
	"sync"

	"github.com/alexei-led/archfit/internal/model/diagnostic"
	"github.com/alexei-led/archfit/internal/model/graph"
	"github.com/alexei-led/archfit/internal/scope"
)

// ExtractorMock is a mock implementation of Extractor for testing.
//
//	func TestSomething(t *testing.T) {
//	    ex := &engine.ExtractorMock{
//	        NameFunc:    func() string { return "go" },
//	        ExtractFunc: func(ctx context.Context, s scope.Scope) (graph.Facts, diagnostic.Coverage, error) { ... },
//	    }
//	    ...
//	}
type ExtractorMock struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// ExtractFunc mocks the Extract method.
	ExtractFunc func(ctx context.Context, s scope.Scope) (graph.Facts, diagnostic.Coverage, error)

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct{}
		// Extract holds details about calls to the Extract method.
		Extract []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S scope.Scope
		}
	}
	lockName    sync.RWMutex
	lockExtract sync.RWMutex
}

// Name calls NameFunc.
func (m *ExtractorMock) Name() string {
	if m.NameFunc == nil {
		panic("ExtractorMock.NameFunc is nil but Extractor.Name was called")
	}
	m.lockName.Lock()
	m.calls.Name = append(m.calls.Name, struct{}{})
	m.lockName.Unlock()
	return m.NameFunc()
}

// NameCalls returns all calls that were made to Name.
func (m *ExtractorMock) NameCalls() []struct{} {
	m.lockName.RLock()
	defer m.lockName.RUnlock()
	calls := make([]struct{}, len(m.calls.Name))
	copy(calls, m.calls.Name)
	return calls
}

// Extract calls ExtractFunc.
func (m *ExtractorMock) Extract(ctx context.Context, s scope.Scope) (graph.Facts, diagnostic.Coverage, error) {
	if m.ExtractFunc == nil {
		panic("ExtractorMock.ExtractFunc is nil but Extractor.Extract was called")
	}
	call := struct {
		Ctx context.Context
		S   scope.Scope
	}{Ctx: ctx, S: s}
	m.lockExtract.Lock()
	m.calls.Extract = append(m.calls.Extract, call)
	m.lockExtract.Unlock()
	return m.ExtractFunc(ctx, s)
}

// ExtractCalls returns all calls that were made to Extract.
func (m *ExtractorMock) ExtractCalls() []struct {
	Ctx context.Context
	S   scope.Scope
} {
	m.lockExtract.RLock()
	defer m.lockExtract.RUnlock()
	calls := make([]struct {
		Ctx context.Context
		S   scope.Scope
	}, len(m.calls.Extract))
	copy(calls, m.calls.Extract)
	return calls
}
