// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package engine

import (
	"context"
	"sync"

	"github.com/alexei-led/archfit/internal/config"
	"github.com/alexei-led/archfit/internal/model/diagnostic"
	"github.com/alexei-led/archfit/internal/scope"
)

// PatternProviderMock is a mock implementation of PatternProvider for testing.
//
//	func TestSomething(t *testing.T) {
//	    pp := &engine.PatternProviderMock{
//	        NameFunc: func() string { return "ast-grep" },
//	        FindFunc: func(ctx context.Context, s scope.Scope, c config.PatternConfig) ([]PatternMatch, diagnostic.Coverage, error) { ... },
//	    }
//	    ...
//	}
type PatternProviderMock struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, s scope.Scope, c config.PatternConfig) ([]PatternMatch, diagnostic.Coverage, error)

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct{}
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S scope.Scope
			// C is the c argument value.
			C config.PatternConfig
		}
	}
	lockName sync.RWMutex
	lockFind sync.RWMutex
}

// Name calls NameFunc.
func (m *PatternProviderMock) Name() string {
	if m.NameFunc == nil {
		panic("PatternProviderMock.NameFunc is nil but PatternProvider.Name was called")
	}
	m.lockName.Lock()
	m.calls.Name = append(m.calls.Name, struct{}{})
	m.lockName.Unlock()
	return m.NameFunc()
}

// NameCalls returns all calls that were made to Name.
func (m *PatternProviderMock) NameCalls() []struct{} {
	m.lockName.RLock()
	defer m.lockName.RUnlock()
	calls := make([]struct{}, len(m.calls.Name))
	copy(calls, m.calls.Name)
	return calls
}

// Find calls FindFunc.
func (m *PatternProviderMock) Find(ctx context.Context, s scope.Scope, c config.PatternConfig) ([]PatternMatch, diagnostic.Coverage, error) {
	if m.FindFunc == nil {
		panic("PatternProviderMock.FindFunc is nil but PatternProvider.Find was called")
	}
	call := struct {
		Ctx context.Context
		S   scope.Scope
		C   config.PatternConfig
	}{Ctx: ctx, S: s, C: c}
	m.lockFind.Lock()
	m.calls.Find = append(m.calls.Find, call)
	m.lockFind.Unlock()
	return m.FindFunc(ctx, s, c)
}

// FindCalls returns all calls that were made to Find.
func (m *PatternProviderMock) FindCalls() []struct {
	Ctx context.Context
	S   scope.Scope
	C   config.PatternConfig
} {
	m.lockFind.RLock()
	defer m.lockFind.RUnlock()
	calls := make([]struct {
		Ctx context.Context
		S   scope.Scope
		C   config.PatternConfig
	}, len(m.calls.Find))
	copy(calls, m.calls.Find)
	return calls
}
