// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package engine

import (
	"context"
	"sync"

	"github.com/alexei-led/archfit/internal/model/diagnostic"
	"github.com/alexei-led/archfit/internal/scope"
)

// SymbolResolverMock is a mock implementation of SymbolResolver for testing.
//
//	func TestSomething(t *testing.T) {
//	    sr := &engine.SymbolResolverMock{
//	        NameFunc:    func() string { return "scip" },
//	        ResolveFunc: func(ctx context.Context, fromFile, toPath string) (string, string) { return toPath, "high" },
//	    }
//	    ...
//	}
type SymbolResolverMock struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(ctx context.Context, fromFile, toPath string) (realPath, confidence string)

	// StrengthsFunc mocks the Strengths method.
	StrengthsFunc func(ctx context.Context, s scope.Scope) (map[string]string, diagnostic.Coverage, error)

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct{}
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FromFile is the fromFile argument value.
			FromFile string
			// ToPath is the toPath argument value.
			ToPath string
		}
		// Strengths holds details about calls to the Strengths method.
		Strengths []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S scope.Scope
		}
	}
	lockName      sync.RWMutex
	lockResolve   sync.RWMutex
	lockStrengths sync.RWMutex
}

// Name calls NameFunc.
func (m *SymbolResolverMock) Name() string {
	if m.NameFunc == nil {
		panic("SymbolResolverMock.NameFunc is nil but SymbolResolver.Name was called")
	}
	m.lockName.Lock()
	m.calls.Name = append(m.calls.Name, struct{}{})
	m.lockName.Unlock()
	return m.NameFunc()
}

// NameCalls returns all calls that were made to Name.
func (m *SymbolResolverMock) NameCalls() []struct{} {
	m.lockName.RLock()
	defer m.lockName.RUnlock()
	calls := make([]struct{}, len(m.calls.Name))
	copy(calls, m.calls.Name)
	return calls
}

// Resolve calls ResolveFunc.
func (m *SymbolResolverMock) Resolve(ctx context.Context, fromFile, toPath string) (string, string) {
	if m.ResolveFunc == nil {
		panic("SymbolResolverMock.ResolveFunc is nil but SymbolResolver.Resolve was called")
	}
	call := struct {
		Ctx      context.Context
		FromFile string
		ToPath   string
	}{Ctx: ctx, FromFile: fromFile, ToPath: toPath}
	m.lockResolve.Lock()
	m.calls.Resolve = append(m.calls.Resolve, call)
	m.lockResolve.Unlock()
	return m.ResolveFunc(ctx, fromFile, toPath)
}

// ResolveCalls returns all calls that were made to Resolve.
func (m *SymbolResolverMock) ResolveCalls() []struct {
	Ctx      context.Context
	FromFile string
	ToPath   string
} {
	m.lockResolve.RLock()
	defer m.lockResolve.RUnlock()
	calls := make([]struct {
		Ctx      context.Context
		FromFile string
		ToPath   string
	}, len(m.calls.Resolve))
	copy(calls, m.calls.Resolve)
	return calls
}

// Strengths calls StrengthsFunc.
func (m *SymbolResolverMock) Strengths(ctx context.Context, s scope.Scope) (map[string]string, diagnostic.Coverage, error) {
	if m.StrengthsFunc == nil {
		panic("SymbolResolverMock.StrengthsFunc is nil but SymbolResolver.Strengths was called")
	}
	call := struct {
		Ctx context.Context
		S   scope.Scope
	}{Ctx: ctx, S: s}
	m.lockStrengths.Lock()
	m.calls.Strengths = append(m.calls.Strengths, call)
	m.lockStrengths.Unlock()
	return m.StrengthsFunc(ctx, s)
}
