package syntax_test

import (
	"testing"

	"github.com/alexei-led/archfit/internal/model/fileclass"
	"github.com/alexei-led/archfit/internal/syntax"
)

func TestClassifyFile_BuiltIn(t *testing.T) {
	noHeader := []byte(nil)
	moqHeader := []byte("// Code generated by moq DO NOT EDIT.\npackage mocks\n")
	genHeader := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n")

	cases := []struct {
		name   string
		lang   string
		path   string
		header []byte
		want   fileclass.FileClass
	}{
		// --- Go production ---
		{name: "go production", lang: "go", path: "internal/core/core.go", header: noHeader, want: fileclass.Production},
		// --- Go test ---
		{name: "go test suffix", lang: "go", path: "internal/core/core_test.go", header: noHeader, want: fileclass.Test},
		// --- Go generated: header ---
		{name: "go generated moq header", lang: "go", path: "internal/mocks/fake_svc.go", header: moqHeader, want: fileclass.Generated},
		{name: "go generated proto header", lang: "go", path: "internal/api/api.pb.go", header: genHeader, want: fileclass.Generated},
		// --- Go generated: filename ---
		{name: "go .pb.go filename", lang: "go", path: "pkg/api/api.pb.go", header: noHeader, want: fileclass.Generated},
		{name: "go mock_ prefix", lang: "go", path: "pkg/x/mock_client.go", header: noHeader, want: fileclass.Generated},
		{name: "go _mock suffix", lang: "go", path: "pkg/x/client_mock.go", header: noHeader, want: fileclass.Generated},
		{name: "go _moq suffix", lang: "go", path: "pkg/x/client_moq.go", header: noHeader, want: fileclass.Generated},
		{name: "go _gen suffix", lang: "go", path: "pkg/x/wire_gen.go", header: noHeader, want: fileclass.Generated},
		// --- TypeScript ---
		{name: "ts production", lang: langTypeScript, path: "src/app.ts", header: noHeader, want: fileclass.Production},
		{name: "ts mts production", lang: langTypeScript, path: "src/app.mts", header: noHeader, want: fileclass.Production},
		{name: "ts test", lang: langTypeScript, path: "src/app.test.ts", header: noHeader, want: fileclass.Test},
		{name: "ts spec", lang: langTypeScript, path: "src/app.spec.ts", header: noHeader, want: fileclass.Test},
		{name: "ts spec mts", lang: langTypeScript, path: "src/app.spec.mts", header: noHeader, want: fileclass.Test},
		{name: "ts test mjs", lang: langTypeScript, path: "src/app.test.mjs", header: noHeader, want: fileclass.Test},
		{name: "ts __tests__", lang: langTypeScript, path: "src/__tests__/app.ts", header: noHeader, want: fileclass.Test},
		{name: "ts .d.ts declaration", lang: langTypeScript, path: "src/types.d.ts", header: noHeader, want: fileclass.Generated},
		{name: "ts .d.mts declaration", lang: langTypeScript, path: "src/types.d.mts", header: noHeader, want: fileclass.Generated},
		{name: "ts .d.cts declaration", lang: langTypeScript, path: "src/types.d.cts", header: noHeader, want: fileclass.Generated},
		{name: "ts .gen.ts", lang: langTypeScript, path: "src/api.gen.ts", header: noHeader, want: fileclass.Generated},
		// --- Python ---
		{name: "python production", lang: langPython, path: "mypackage/core.py", header: noHeader, want: fileclass.Production},
		{name: "python test_ prefix", lang: langPython, path: "tests/test_core.py", header: noHeader, want: fileclass.Test},
		{name: "python _test suffix", lang: langPython, path: "mypackage/core_test.py", header: noHeader, want: fileclass.Test},
		{name: "python tests/ segment", lang: langPython, path: "mypackage/tests/helpers.py", header: noHeader, want: fileclass.Test},
		{name: "python _pb2 generated", lang: langPython, path: "mypackage/api_pb2.py", header: noHeader, want: fileclass.Generated},
		// --- Rust ---
		{name: "rust production", lang: "rust", path: "src/lib.rs", header: noHeader, want: fileclass.Production},
		{name: "rust tests/ segment", lang: "rust", path: "tests/integration.rs", header: noHeader, want: fileclass.Test},
		// --- Vendor ---
		{name: "vendor path", lang: "go", path: "vendor/github.com/pkg/x.go", header: noHeader, want: fileclass.Vendor},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := syntax.ClassifyFile(tc.lang, tc.path, tc.header, syntax.FileClassConfig{})
			if got != tc.want {
				t.Errorf("ClassifyFile(%q, %q) = %q, want %q", tc.lang, tc.path, got, tc.want)
			}
		})
	}
}

func TestClassifyFile_ConfigOverride(t *testing.T) {
	cfg := syntax.FileClassConfig{
		// Custom mock framework: files prefixed "fake_" should be Generated.
		MockFrameworks: []string{"fake_"},
		// Custom test glob: files in testutil/ should be Test.
		TestGlobs: []string{"testutil/*"},
		// Custom generated glob: anything under generated/ directory.
		GeneratedGlobs: []string{"generated/"},
	}

	cases := []struct {
		name string
		lang string
		path string
		want fileclass.FileClass
	}{
		// Custom mock framework.
		{name: "fake_ prefix → Generated", lang: "go", path: "pkg/x/fake_client.go", want: fileclass.Generated},
		// Regular production file not reclassified.
		{name: "normal file → Production", lang: "go", path: "pkg/x/client.go", want: fileclass.Production},
		// Custom test glob.
		{name: "testutil/ glob → Test", lang: "go", path: "testutil/helpers.go", want: fileclass.Test},
		// Custom generated glob (directory segment).
		{name: "generated/ dir → Generated", lang: "go", path: "generated/api.go", want: fileclass.Generated},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := syntax.ClassifyFile(tc.lang, tc.path, nil, cfg)
			if got != tc.want {
				t.Errorf("ClassifyFile(%q, %q) = %q, want %q", tc.lang, tc.path, got, tc.want)
			}
		})
	}
}

func TestLookupFileClass_IndexHit(t *testing.T) {
	index := map[string]fileclass.FileClass{
		"pkg/core/core.go":  fileclass.Production,
		"pkg/mocks/fake.go": fileclass.Generated,
	}
	cfg := syntax.FileClassConfig{}

	got := syntax.LookupFileClass("pkg/core/core.go", index, "go", cfg)
	if got != fileclass.Production {
		t.Errorf("index hit: got %q, want production", got)
	}

	got = syntax.LookupFileClass("pkg/mocks/fake.go", index, "go", cfg)
	if got != fileclass.Generated {
		t.Errorf("index hit mock: got %q, want generated", got)
	}
}

func TestLookupFileClass_FallbackPathOnly(t *testing.T) {
	// Empty index — falls back to path-only classification (no header).
	// This simulates files in loc's skipDirs (e.g. mocks/) that never appear
	// in the FileClassIndex.
	index := map[string]fileclass.FileClass{}
	cfg := syntax.FileClassConfig{}

	// mock_*.go should be classified Generated via filename even without index.
	got := syntax.LookupFileClass("mocks/mock_client.go", index, "go", cfg)
	if got != fileclass.Generated {
		t.Errorf("fallback mock: got %q, want generated", got)
	}

	// _test.go should be classified Test via filename.
	got = syntax.LookupFileClass("pkg/x/x_test.go", index, "go", cfg)
	if got != fileclass.Test {
		t.Errorf("fallback test: got %q, want test", got)
	}

	// Normal production file.
	got = syntax.LookupFileClass("pkg/x/x.go", index, "go", cfg)
	if got != fileclass.Production {
		t.Errorf("fallback production: got %q, want production", got)
	}
}

// TestClassifyFile_DoublestareGlobs verifies M2: user-supplied file_class globs
// that use ** doublestar patterns match correctly via doublestar.Match.
func TestClassifyFile_DoublestarGlobs(t *testing.T) {
	cfg := syntax.FileClassConfig{
		// Doublestar generated glob: any file under any "generated" directory.
		GeneratedGlobs: []string{"**/generated/*.go"},
		// Doublestar test glob: any file under any "testdata" directory.
		TestGlobs: []string{"testdata/**"},
	}

	cases := []struct {
		name string
		path string
		want fileclass.FileClass
	}{
		// ** generated glob: matches files at any depth.
		{name: "generated/ at root", path: "generated/api.go", want: fileclass.Generated},
		{name: "generated/ nested", path: "pkg/internal/generated/model.go", want: fileclass.Generated},
		// ** test glob.
		{name: "testdata/ nested", path: "testdata/fixtures/data.go", want: fileclass.Test},
		// Non-matching paths remain Production.
		{name: "production file", path: "pkg/core/core.go", want: fileclass.Production},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := syntax.ClassifyFile("go", tc.path, nil, cfg)
			if got != tc.want {
				t.Errorf("ClassifyFile(%q) = %q, want %q", tc.path, got, tc.want)
			}
		})
	}
}

// TestClassifyFile_EmptyMockFramework is a regression test for D1: an empty
// string in MockFrameworks must not classify every production file as Generated
// (strings.HasPrefix(base,"") is always true).
func TestClassifyFile_EmptyMockFramework(t *testing.T) {
	cfg := syntax.FileClassConfig{
		MockFrameworks: []string{"", "mock_"}, // empty entry must be skipped
	}
	cases := []struct {
		path string
		want fileclass.FileClass
	}{
		{"pkg/service/service.go", fileclass.Production},
		{"internal/handler/http.go", fileclass.Production},
		{"mock_user.go", fileclass.Generated}, // legitimate mock prefix still works
	}
	for _, tc := range cases {
		t.Run(tc.path, func(t *testing.T) {
			got := syntax.ClassifyFile("go", tc.path, nil, cfg)
			if got != tc.want {
				t.Errorf("ClassifyFile(%q) with empty MockFrameworks entry = %q, want %q", tc.path, got, tc.want)
			}
		})
	}
}
